In [1]:
import pandas as pd
import numpy as np

#### 파일 불러오기

In [2]:
input_fd = open('C:/Users/user/ESAA/youtube-new/KRvideos.csv',errors = 'backslashreplace',encoding='utf-8')
KR = pd.read_csv(input_fd, sep=',')

input_fd = open('C:/Users/user/ESAA/youtube-new/JPvideos.csv', errors = 'backslashreplace',encoding='utf-8')
JP = pd.read_csv(input_fd, sep=',')

US = pd.read_csv('C:/Users/user/ESAA/youtube-new/USvideos.csv', sep=',')

#### 파일이 잘 입력되었는지, 문자 깨짐은 없는지 확인 

In [3]:
print(KR.shape)
print(JP.shape)
print(US.shape)

(34567, 16)
(20523, 16)
(40949, 16)


In [4]:
print(KR.head())
print(JP.head())
print(US.head())

      video_id trending_date                       title channel_title  \
0  RxGQe4EeEpA      17.14.11          좋아 by 민서_윤종신_좋니 답가        라푸마코리아   
1  hH7wVE8OlQ0      17.14.11            JSA 귀순 북한군 총격 부상        Edward   
2  9V8bnWUmE9U      17.14.11  나몰라패밀리 운동화 영상 2탄 (빼빼로데이버젼)     나몰라패밀리 핫쇼   
3  0_8py-t5R80      17.14.11  이명박 출국 현장, 놓치면 안되는 장면         미디어몽구   
4  bk55RbxiQdI      17.14.11     김장겸은 물러갔다 MBC 노조 환호와 눈물        NocutV   

   category_id              publish_time  \
0           22  2017-11-13T07:07:36.000Z   
1           25  2017-11-13T10:59:16.000Z   
2           22  2017-11-11T07:16:08.000Z   
3           25  2017-11-12T11:19:52.000Z   
4           25  2017-11-13T11:08:59.000Z   

                                                tags   views  likes  dislikes  \
0                      라푸마|"윤종신"|"좋니"|"좋아"|"샬레"|"민서"  156130   1422        40   
1        JSA|"귀순"|"북한군"|"총격"|"부상"|"JSA 귀순 북한군 총격 부상"   76533    211        28   
2                아디다스|"빼빼로"|"핫쇼"|"나몰라패밀리"|"대학로"

#### 변수명 확인

In [5]:
KR.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

## 목표(확인하고 싶은 insight)
1. 평균 like 수, 
2. 일정 like 수 이상인 글의 비율
3. like/dislike 비율
4. category별 평균 views
5. top 5 view category
6. comment count/views 비율
7. likes views 관계

* 전체 국가를 고려하지 않고 한, 미, 일 세 개의 국가만 분석 대상으로 선택

### 4.category별 평균 views
각 국가에서 카테고리별 평균 조회수 확인

각 국가의 category_id, views 변수만 추출한 데이터를 만든다.

In [6]:
KR_C = KR.loc[:,['category_id', 'views']]
JP_C = JP.loc[:,['category_id', 'views']]
US_C = US.loc[:,['category_id', 'views']]

NA 확인

In [7]:
print(np.count_nonzero(KR_C.isnull()))
print(np.count_nonzero(JP_C.isnull()))
print(np.count_nonzero(US_C.isnull()))

0
0
0


In [8]:
print(KR_C.count())
print(JP_C.count())
print(US_C.count())

category_id    34567
views          34567
dtype: int64
category_id    20523
views          20523
dtype: int64
category_id    40949
views          40949
dtype: int64


In [9]:
print(np.sort(KR_C['category_id'].unique()))
print(np.sort(JP_C['category_id'].unique()))
print(np.sort(US_C['category_id'].unique()))

[ 1  2 10 15 17 19 20 22 23 24 25 26 27 28 29 43 44]
[ 1  2 10 15 17 19 20 22 23 24 25 26 27 28 29]
[ 1  2 10 15 17 19 20 22 23 24 25 26 27 28 29 43]


In [10]:
KR_C.rename(columns = {'views' : 'views_KR'}, inplace = True)
KR_Cmean = KR_C.groupby('category_id').mean()
JP_C.rename(columns = {'views' : 'views_JP'}, inplace = True)
JP_Cmean = JP_C.groupby('category_id').mean()
US_C.rename(columns = {'views' : 'views_US'}, inplace = True)
US_Cmean = US_C.groupby('category_id').mean()

In [11]:
print(KR_Cmean)
print(JP_Cmean)
print(US_Cmean)

                 views_KR
category_id              
1            5.440154e+05
2            1.198672e+05
10           2.080543e+06
15           2.022284e+05
17           5.987503e+05
19           2.405090e+05
20           2.814424e+05
22           2.098027e+05
23           3.598452e+05
24           5.103813e+05
25           1.546775e+05
26           3.146176e+05
27           1.511617e+05
28           2.685160e+06
29           6.316461e+04
43           1.062983e+05
44           1.664950e+04
                 views_JP
category_id              
1            2.554023e+05
2            8.319242e+04
10           8.297243e+05
15           6.271681e+04
17           2.850889e+05
19           1.032965e+05
20           1.684717e+05
22           1.500606e+05
23           3.781614e+05
24           2.821966e+05
25           1.338265e+05
26           1.356909e+05
27           8.666788e+04
28           1.213748e+06
29           9.003361e+04
                 views_US
category_id              
1           

### 5.top 5 view category
세 국가에서 인기있는 카테고리를 비교하고 평균적으로 인기있는 카테고리 알아보기

In [12]:
CTGRY = pd.merge(KR_Cmean, JP_Cmean, on = 'category_id')
CTGRY = pd.merge(CTGRY, US_Cmean, on = 'category_id')

In [13]:
CTGRY['views_KR'] = CTGRY['views_KR']/100000
CTGRY['views_JP'] = CTGRY['views_JP']/100000
CTGRY['views_US'] = CTGRY['views_US']/100000
CTGRY['views_mean'] = (CTGRY['views_KR'] + CTGRY['views_JP'] + CTGRY['views_US'])/3
print(CTGRY.shape)
print(CTGRY)
#조회수 단위는 십만.

(15, 4)
              views_KR   views_JP   views_US  views_mean
category_id                                             
1             5.440154   2.554023  31.062502   13.018893
2             1.198672   0.831924  13.559654    5.196750
10           20.805435   8.297243  62.010031   30.370903
15            2.022284   0.627168   8.311435    3.653629
17            5.987503   2.850889  20.259690    9.699361
19            2.405090   1.032965   8.546196    3.994750
20            2.814424   1.684717  26.208306   10.235816
22            2.098027   1.500606  15.318354    6.305662
23            3.598452   3.781614  14.803084    7.394383
24            5.103813   2.821966  20.678832    9.534870
25            1.546775   1.338265   5.925877    2.936972
26            3.146176   1.356909   9.837301    4.780128
27            1.511617   0.866679   7.129408    3.169234
28           26.851597  12.137482  14.526267   17.838449
29            0.631646   0.900336  29.638841   10.390274


세 국가의 유튜브 조회수가 크게 차이가 난다.  
10번 카테고리는 세 국가 모두 높은 조회수를 기록한다.  
한국에서는 특히 28번 카테고리 조회수가 높고 미국은 1번, 29번이 높다.  
28번은 한국과 일본 모두 조회수가 높은 데 반해 미국에서는 오히려 조회수가 낮다.